server:
    http_listen_port: 3200

distributor:
    receivers:
        otlp:
            protocols:
                grpc:
                    endpoint: "0.0.0.0:14317"
                http:
                    endpoint: "0.0.0.0:14318"

ingester:
    trace_idle_period: 10s

compactor:
    compaction:
        compacted_block_retention: 48h

storage:
    trace:
        backend: local
        local:
            path: /var/tempo/traces